all:
	g++ ./source/main.cpp
	./a.out <./test/test1.txt
	./a.out <./test/test2.txt
	./a.out <./test/test3.txt
	./a.out <./test/test4.txt
	./a.out <./test/test5.txt
	./a.out <./test/test6.txt
	./a.out <./test/test7.txt
	./a.out <./test/test8.txt
	./a.out <./test/test9.txt
	
	cat ./test/answer

valg:
	g++ ./source/main.cpp
	valgrind ./a.out <./test/test1.txt
	valgrind ./a.out <./test/test2.txt
	valgrind ./a.out <./test/test3.txt
	valgrind ./a.out <./test/test4.txt
	valgrind ./a.out <./test/test5.txt
	valgrind ./a.out <./test/test6.txt
	valgrind ./a.out <./test/test7.txt
	valgrind ./a.out <./test/test8.txt
	valgrind ./a.out <./test/test9.txt